### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by techakki81** [pnp/m365-hosted-apps-vscode#1]
Two issues which i encountered while on Windows PC

1.  Installed the app in VSCode. The PNP icon started showing -> ok 
2. Created a new project using the Planner template .  The source code was copied to my local drive but VS code gave the following error "File system provider for c:. is not available."
3. I also could not open the newly created project in VSCode. 

So uninstalled and installed the app again. But this time now the Pnp icon does not show up at all (see image)

Good idea btw :-) 

<img width="957" alt="installation" src="https://user-images.githubusercontent.com/5646605/171371660-110df617-da26-4040-a40a-d51cbe39ca92.PNG">

**Comment by estruyf** [comment]
Thanks, @techakki81 for opening the first issue. Can you check what is created on your file system?

**Comment by techakki81** [comment]
thanks @estruyf ... all the fiiles are created on the local drive for the project. 
Also, i confirm it works on my personal mac but not on corp windows pc. It very well could be some specific security setting of the organisation

**Comment by estruyf** [comment]
New update is on the way for Windows.
